version: '3.8'

services:
  web:
    image: nginx:1.23-alpine
    container_name: Coffee-web
    working_dir: /application
    volumes:
      - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - Coffee-dev
    ports:
      - ${EXTERNAL_WEBSERVER_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - php
      - database

  php:
    build:
      context: environment/dev/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    container_name: Coffee-php
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
      - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - Coffee-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: Coffee-redis
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    volumes:
      - Coffee-redis-data:/data
    networks:
      - Coffee-dev
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: Coffee-db
    environment:
      - PGPASSWORD=${DOCKER_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-5432}:5432
    volumes:
      - Coffee-pgsql-data:/var/lib/postgresql/data
    networks:
      - Coffee-dev
    restart: unless-stopped

  node:
    image: node:19-alpine3.16
    container_name: Coffee-node
    working_dir: /application
    tty: true
    volumes:
        - .:/application
    networks:
        - Coffee-dev
    ports:
        - "5173:5173"
    restart: unless-stopped

networks:
  Coffee-dev:
    driver: bridge

volumes:
  Coffee-pgsql-data:
    name: Coffee-pgsql-data
  Coffee-redis-data:
    name: Coffee-redis-data
